2022-01-11 11:01:48,642 INFO    MainThread:67312 [internal.py:wandb_internal():90] W&B internal server running at pid: 67312, started at: 2022-01-11 11:01:48.642206
2022-01-11 11:01:48,647 INFO    WriterThread:67312 [datastore.py:open_for_write():77] open: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\run-3fkmjmz7.wandb
2022-01-11 11:01:48,649 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: check_version
2022-01-11 11:01:48,653 DEBUG   SenderThread:67312 [sender.py:send():238] send: header
2022-01-11 11:01:48,654 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: check_version
2022-01-11 11:01:49,698 DEBUG   SenderThread:67312 [sender.py:send():238] send: run
2022-01-11 11:01:49,703 INFO    SenderThread:67312 [sender.py:_maybe_setup_resume():506] checking resume status for None/U-Net/3fkmjmz7
2022-01-11 11:01:50,519 INFO    SenderThread:67312 [dir_watcher.py:__init__():169] watching files in: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files
2022-01-11 11:01:50,519 INFO    SenderThread:67312 [sender.py:_start_run_threads():828] run started: 3fkmjmz7 with start time 1641870107
2022-01-11 11:01:50,519 DEBUG   SenderThread:67312 [sender.py:send():238] send: summary
2022-01-11 11:01:50,520 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: run_start
2022-01-11 11:01:50,529 INFO    SenderThread:67312 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-01-11 11:01:50,560 DEBUG   HandlerThread:67312 [meta.py:__init__():40] meta init
2022-01-11 11:01:50,561 DEBUG   HandlerThread:67312 [meta.py:__init__():54] meta init done
2022-01-11 11:01:50,561 DEBUG   HandlerThread:67312 [meta.py:probe():214] probe
2022-01-11 11:01:50,682 DEBUG   HandlerThread:67312 [meta.py:_setup_git():204] setup git
2022-01-11 11:01:50,826 DEBUG   HandlerThread:67312 [meta.py:_setup_git():211] setup git done
2022-01-11 11:01:50,826 DEBUG   HandlerThread:67312 [meta.py:_save_pip():58] save pip
2022-01-11 11:01:50,827 DEBUG   HandlerThread:67312 [meta.py:_save_pip():72] save pip done
2022-01-11 11:01:50,828 DEBUG   HandlerThread:67312 [meta.py:_save_conda():79] save conda
2022-01-11 11:01:51,525 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\conda-environment.yaml
2022-01-11 11:01:51,525 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\requirements.txt
2022-01-11 11:01:51,526 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\wandb-summary.json
2022-01-11 11:01:56,535 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\output.log
2022-01-11 11:01:57,538 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\conda-environment.yaml
2022-01-11 11:01:58,339 DEBUG   HandlerThread:67312 [meta.py:_save_conda():89] save conda done
2022-01-11 11:01:58,339 DEBUG   HandlerThread:67312 [meta.py:probe():252] probe done
2022-01-11 11:01:58,356 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:01:58,357 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:01:58,541 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\conda-environment.yaml
2022-01-11 11:01:58,541 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\output.log
2022-01-11 11:01:58,542 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\wandb-metadata.json
2022-01-11 11:01:58,875 DEBUG   SenderThread:67312 [sender.py:send():238] send: config
2022-01-11 11:01:58,876 DEBUG   SenderThread:67312 [sender.py:send():238] send: files
2022-01-11 11:01:58,877 INFO    SenderThread:67312 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-01-11 11:02:00,056 INFO    Thread-22 :67312 [upload_job.py:push():137] Uploaded file C:\Users\211001~1.WXC\AppData\Local\Temp\tmpk8ns7cs4wandb\38tl2b58-wandb-metadata.json
2022-01-11 11:02:13,877 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:02:13,878 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:02:20,369 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:02:20,605 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\config.yaml
2022-01-11 11:02:29,265 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:02:29,266 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:02:44,629 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:02:44,629 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:02:51,522 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:03:00,008 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:03:00,009 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:03:15,389 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:03:15,389 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:03:22,576 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:03:30,755 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:03:30,756 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:03:46,152 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:03:46,152 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:03:53,633 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:04:01,528 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:04:01,528 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:04:16,932 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:04:16,932 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:04:24,695 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:04:32,304 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:04:32,304 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:04:47,679 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:04:47,680 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:04:55,785 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:05:03,060 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:05:03,060 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:05:18,438 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:05:18,439 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:05:26,850 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:05:33,805 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:05:33,805 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:05:49,169 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:05:49,169 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:05:57,941 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:06:04,542 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:06:04,542 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:06:19,926 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:06:19,926 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:06:29,012 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:06:35,638 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:06:35,638 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:06:51,006 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:06:51,008 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:07:00,090 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:07:06,385 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:07:06,386 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:07:21,757 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:07:21,758 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:07:31,161 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:07:37,146 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:07:37,146 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:07:52,528 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:07:52,528 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:08:02,256 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:08:07,997 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:08:07,998 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:08:23,385 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:08:23,386 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:08:33,334 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:08:38,763 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:08:38,763 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:08:54,128 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:08:54,129 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:09:04,501 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:09:09,605 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:09:09,606 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:09:24,978 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:09:24,979 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:09:35,777 DEBUG   SenderThread:67312 [sender.py:send():238] send: stats
2022-01-11 11:09:42,142 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:09:42,143 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:09:57,553 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:09:57,553 DEBUG   SenderThread:67312 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:10:00,982 ERROR   SenderThread:67312 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
2022-01-11 11:10:06,054 WARNING FileStreamThread:67312 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001AD3203D940>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:10:08,085 WARNING FileStreamThread:67312 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001AD3203D940>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:10:12,355 WARNING FileStreamThread:67312 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001AD3203D940>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:10:17,555 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:10:20,452 WARNING FileStreamThread:67312 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001AD3203D940>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:10:37,557 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:10:40,269 WARNING FileStreamThread:67312 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001AD3203D940>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/3fkmjmz7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:10:45,944 WARNING MainThread:67312 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-11 11:10:46,809 DEBUG   HandlerThread:67312 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:10:47,408 INFO    Thread-17 :67312 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_110145-3fkmjmz7\files\output.log
